# Add a 'backend' label if files change within the 'backend' directory
backend:
  - 'backend/**'

# Add a 'frontend' label if files change within the 'frontend' or 'ui' directories
frontend:
  - 'frontend/**'

# Add a 'workflow' label if files change within the 'workflow' directory or any markdown files
workflow:
  - '.github/workflows/**'
  - '*.yml'
  - '*.yaml'
  - 'jenkins/**'
